set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARCV3-HS6X)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_C_COMPILER arc64-elf-gcc)
set(CMAKE_CXX_COMPILER arc64-elf-g++)

set(ARC64_HS6X_FLAGS "-Os -mcpu=arc64")
set(CMAKE_C_FLAGS "${ARC64_HS6X_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${ARC64_HS6X_FLAGS}" CACHE STRING "" FORCE)
